phrase=("Bladh cdef gidjk")
print(phrase.lower())
phrase=(phrase.upper())
print(phrase.islower())
print(phrase.isupper())
print(phrase.lower().islower())
print(len(phrase))
print(phrase[10])
print(phrase.index("A"))
print(phrase.replace("BLADH","mnop"))
print(phrase)
print("Right most d",phrase.rindex("D"))
print(phrase[1:5])
print(phrase.index("F"))