list=["Kevin","Robin","Tim"]
numbers=[1,2,3,4,5,6,7,8,9,10]
print("The complete list is" ,list)
print("The first element is" ,list[0])
print("The second element is" ,list[1])
print("The third element is" ,list[2])
print("The fourth element is" ,list[-1])
print(list[1:])
print(numbers)
numbers.extend(list)
print("After extend the numbered list is" ,numbers)
list.append("Jhonny")
print("After append the list is" ,list)
list.insert(4,"Gambhir")
list.insert(1,"Kevin")
print("After insert the list is" ,list)
list.remove("Tim")
print("After remove the list is" ,list)
list.pop()
print("After pop the list is" ,list)
print(list.index("Kevin"))
print(list.count("Kevin"))
list.sort()
print("After sorting the list is" ,list)
numbers.reverse()
print("After reverse the numbered list is" ,numbers)
list2=list.copy()
list.clear()
print("After clear the list is" ,list)

